# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root/nixos";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9B0A-B13A";
      fsType = "vfat";
    };

  fileSystems."/var/lib/lancache" =
    { device = "dpool/lancache";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/var/lib/prometheus" =
    { device = "dpool/prometheus";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/var/lib/loki" =
    { device = "dpool/loki";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/var/log/lancache" =
    { device = "dpool/logs/lancache";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
