# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6d69f148-b5b5-4c1c-9f27-3baa01d88961";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."root" = { 
    device = "/dev/disk/by-uuid/0913077f-51ce-4d6c-a56f-ea2268caf1e0";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6F89-A011";
    fsType = "vfat";
  };

  fileSystems."/home/francis" = {
    device = "/dev/disk/by-uuid/8301b1da-926e-49fb-beab-9f8fa06563eb";
    fsType = "ext4";
    encrypted.enable = true;
    encrypted.blkDev = "/dev/disk/by-uuid/d45dab13-cff5-4035-aed2-0f57f64ec5b0";
    encrypted.keyFile = "/mnt-root/etc/luks/keys/home.key";
    encrypted.label = "francis-home";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/199fb1c4-8a19-49aa-86fa-ac15ca5790d5"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
