# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "SystemPool/root";
    fsType = "zfs"; options = [ "zfsutil" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BD77-EA55";
    fsType = "vfat";
  };

  fileSystems."/nix" = {
    device = "SystemPool/nix";
    fsType = "zfs"; options = [ "zfsutil" ];
  };

  fileSystems."/home/francis" = {
    device = "SlowStoragePool/francis/home";
    fsType = "zfs"; options = [ "zfsutil" ];
  };

  fileSystems."/home/francis/.games" ={
    depends = [ "/home/francis" ];
    device = "StoragePool/francis/games";
    fsType = "zfs"; options = [ "zfsutil" ];
  };

  fileSystems."/home/francis/Documents" = {
    depends = [ "/home/francis" ];
    device = "StoragePool/francis/docs";
    fsType = "zfs"; options = [ "zfsutil" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/e543ec3e-4552-4315-a970-e98ebed98750"; }
  ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
