let g:go_fmt_command = 'goimports'
let g:go_auto_type = 1
let g:go_auto_type_info = 1
let g:go_template_autocreate = 0
let g:go_gocode_unimported_packages = 1
let g:go_gopls_complete_unimported = 1
let g:go_bin_path= '~/.go/bin'
let g:go_def_mode= '~/.go/bin/gopls'
let g:go_info_mode='gopls'
