[theme]
theme = "srcery"
[theme.overrides]

[icons]
icons = "awesome6"

[[block]]
block = "keyboard_layout"
driver = "localebus"
format = "$layout / $variant"

[[block]]
block = "music"
player = "spotify"
format = "$icon {$combo.str(max_w:20) $play $next |}"
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"

[[block]]
block = "sound"

[[block]]
block = "net"
format = " $icon {$ssid $signal_strength $frequency|Wired} $ip $ipv6"
interval = 30

[[block]]
block = "disk_space"
path = "/home/francis"
info_type = "available"
interval = 600
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 600
warning = 10.0
alert = 5.0

[[block]]
block = "memory"
interval = 30

[[block]]
block = "battery"
interval = 10
format = "$icon $percentage($time)"

[[block]]
block = "load"
interval = 300
format = " $icon $5m.eng(w:4)/$15m.eng(w:4)"

[[block]]
block = "time"
interval = 60
