[providers.consul]
    endpoints = ["10.3.10.10:8500"]

[entryPoints]
    [entryPoints.web]
    address = ":80"
            [entryPoints.web.http.redirections]
                [entryPoints.web.http.redirections.entryPoint]
                    to = "websecure"
                    scheme = "https"
    [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.personal.acme]
    email = "francis.begyn@gmail.com"
    storage = "/var/lib/traefik/acme.json"
    [certificatesResolvers.personal.acme.httpChallenge]
        entryPoint = "web"

[metrics]
    [metrics.prometheus]
        manualRouting = true

[api]
    dashboard = true

[log]
    filePath = "/var/log/traefik/traefik.log"
    level = "DEBUG"

[accessLog]
    filePath = "/var/log/traefik/access.log"
    bufferingSize = 100
