# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "xhci_pci" "ahci" "firewire_ohci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."system" = {
    device = "/dev/disk/by-uuid/ec9a985a-ae04-4811-a2e3-34abf177e87b";
    preLVM = false;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2f9c6cdf-46ef-49ee-a2ec-f7aedf332206";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E123-1947";
      fsType = "vfat";
    };

  boot.initrd.luks.devices."home-francis" = {
    name = "home-francis";
    device = "/dev/disk/by-uuid/3dec0df7-29d1-429a-a569-93839b606158";
    preLVM = false;
  };

  fileSystems."/home/francis" =
    { device = "/dev/disk/by-uuid/04a6a316-2adc-4501-b149-3fe62d971f01";
      fsType = "ext4";
    };

  swapDevices = [{ device = "/dev/disk/by-uuid/cf2529ad-a482-4f2c-82a5-ee9831b4ff52"; }];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # High-DPI console
  console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
