---
name: update-flake-lock
on:
  schedule:
    - cron: '0 7 * * */2'

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Update flake.lock
        shell: bash
        env:
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
          GIT_COMMITER_NAME: "github-actions[bot]"
          GIT_COMMITER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          nix flake update --commit-lock-file
          git push origin main
